### ISSUE TITLE
Support Conversation for version 2

### ISSUE THREAD

**Issue by royuen** [SkygearIO/chat#50]
### Tentative doc:
[conversation.md](https://github.com/rickmak/chat/blob/master/doc/conversation.md)

### Supporting API
- createConversation(participants, title, options)
- deleteConversation(conversation)
- updateConversation(conversation)
- addParticipants(conversation, participants)
- removeParticipants(conversation, participants)
- addAdmins(conversation, admins)
- removeAdmins(conversation, admins)
- getUserConversations()
- getUserConversation(conversation)

### Tasks (Plugin)
- [x] support `distinct_by_participants` and remove `is_direct_message`

### Tasks (SDKs)
- [ ] move `admin` to `options` when conversation creation (make it optional)
- [ ] support delete conversation

**Comment by ben181231** [comment]
### TODOs
- [ ] support `distinctByParticipants`
- [ ] move `admin` to `options` when conversation creation (make it optional)
- [ ] support delete conversation on SDKs
